### PR TITLE
Add new technique - Bootstrap aggregating

### PR DESCRIPTION
**Pull request by UlrikeS91**
from https://github.com/openMetadataInitiative/openMINDS_controlledTerms/pull/217 

Only issue was the name of the technique and I think "bootstrap aggregating" sounds ok. This seems to be the standard and I don't feel it sounds incomplete (although I know what you mean @lzehl).

### CODE REVIEW

**Review by lzehl — CHANGES_REQUESTED** [review]
needs to be defined for AnalysisTechnique

**Comment by UlrikeS91** [comment]
moved to analysis technique and ready for final check @lzehl

**Review by lzehl — COMMENTED** [review]
updated to new namespace and populated to other version folders @Raphael-Gazzotti please double check and merge if okay (and delete then the branch).

**Review by lzehl — COMMENTED** [review]
@Raphael-Gazzotti okay now? there was again different tab settings in the github editor...

**Comment by Raphael-Gazzotti** [comment]
The JSON formatting still doesn't appear as expected unless the indentation is set to 2 spaces in GitHub's editing mode. However, I'm unsure if this change will be consistently applied.

**Review by lzehl — COMMENTED** [review]
@Raphael-Gazzotti another try... I don't get github here

**Review by Raphael-Gazzotti — APPROVED** [review]

**Pull request merged**
