### PR TITLE
Namespace Change and Version Management

### PR DESCRIPTION
**Pull request by Raphael-Gazzotti**
Update of namespace for v4.0 and latest, removal of MRIPulseSequence and MRIWeighting in versions v3.0 and v4.0.

### CODE REVIEW

**Review by lzehl — CHANGES_REQUESTED** [review]
the types in latest need the submodule removed from the namespace

**Review by lzehl — APPROVED** [review]
checked in @Raphael-Gazzotti repo

**Comment by lzehl** [comment]
@apdavison @ehennestad does this merge cause issues in the Python and MATLAB package?

**Comment by apdavison** [comment]
> _does this merge cause issues in the Python...package?_

Probably, but I'm anyway expecting to have to update the build pipeline for the Python package once the main pipeline is updated.

**Comment by ehennestad** [comment]
Yes, but I have also started to update the build pipeline and have temporarily deactivated the GitHub build workflow due to the changes in namespaces for submodules already causing some issues

**Comment by lzehl** [comment]
@apdavison @ehennestad Then I can merge?

**Pull request merged**
